### ISSUE TITLE
Finding time zones is hard.

### ISSUE THREAD

**Issue by calleluks** [linduxed/rmnd.io#14]
If one does not know that a time zone is prioritized it can sometimes be hard to find it in the select box.

**Comment by talltorp** [comment]
How about also including the prioritized time zones in general list of time zones?

That way you can both find them fast if you look in the prioritized section.
If you miss them, you will still be able to find them in the expected place in the list.

I immediately scrolled down to +1 GMT and expected Stockholm to be there. Because thats the way most "time-zone"-pickers that I have used work.

**Comment by calleluks** [comment]
That's a great idea. The rails [`#time_zone_select` helper](http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-time_zone_select) does not seem to support this, though.

I think the easiest solution is to just not prioritize any time zone. This could be enhanced by checking the browser's time zone with JavaScript and selecting it on page load so that the user doesn't need to actually select it.
